version: '3'

services:
  frontend:
    image: gautampatil1/pictopixie-client:latest
    ports:
      - "6000:3000"
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_PORT=0


  backend:
    image: gautampatil1/pictopixie-server:latest
    ports:
      - "4000:8000"
    